[managers.system]
items = [
  "git",
  "swayfx",
  "swaybg",
  "waybar", 
  "wofi", 
  "aylurs-gtk-shell", 
  "otf-font-awesome", 
  "ttf-firacode-nerd", 
  "flavours", "stow", 
  "tree", 
  "zsh", 
  "fish", 
  "kitty", 
  "neovim", 
  "ripgrep", 
  "fzf", 
  "luarocks", 
  "ueberzugpp", 
  "chafa", 
  "openslide", 
  "sc-im", 
  "hyprpicker", 
  "slurp", 
  "grim", 
  "swayimg", 
  "wl-clipboard", 
  "qutebrowser", 
  "nodejs"
]
