[managers.system]
items = [
  # Git
  "git",

  # Sway
  "swayfx",
  "swaybg",

  # Widgets 
  "waybar",           #Remove when done with ags
  "wofi",
  "aylurs-gtk-shell",
  "dunst",            #Remove when done with ags, maybe, in the future

  # Font
  "otf-font-awesome",
  "ttf-firacode-nerd",

  # Japanese Font
  "ttf-koruri",
  "fcitx5",
  "fcitx5-configtool",
  "fcitx5-gtk",
  "fcitx5-qt",
  "fcitx5-mozc",

  # Themer
  "flavours",

  # Symlinks
  "stow",

  # Neovim
  "tree",
  "zsh",
  "fish",        # System related
  "kitty",
  "neovim",
  "ripgrep",
  "fzf",
  "luarocks",
  "zsh-vi-mode",

  # Image viewer
  "ueberzugpp",
  "chafa",
  "openslide",

  # Excel
  "pdfjs",
  "libreoffice-fresh",

  # Color picker
  "hyprpicker",

  # Screen Capture
  "slurp",
  "grim",
  "swayimg",
  "wl-clipboard",
  "wf-recorder",

  # Font viewer
  "fontforge",

  # Browser
  "qutebrowser",

  # Javascript
  "nodejs",

  # Note taking
  "deno",
]
